name: Pulumi Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    if: ${{ vars.PULUMI_STACK_NAME != '' && vars.AWS_ROLE_TO_ASSUME != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Pulumi Up
        uses: ./.github/actions/pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: up
          stack-name: ${{ vars.PULUMI_STACK_NAME }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
          aws-role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          infisical-external-id: ${{ secrets.INFISICAL_EXTERNAL_ID }}
